### ISSUE TITLE
Add multitasking support

### ISSUE THREAD

**Issue by Thinkscape** [LabAdvComp/cloudfuse#17]
Currently all I/O ops are blocking each other. i.e. once a copy is initiated, all other stat calls are blocked (frozen). It'd make a lot of difference if dir ops (like readdir) were executed on a separate thread, while `n` number of read/write operations were executed on other threads. 

This applies to both the internal threading (for handling calls) and request parallelization (i.e. how many HTTP requests can be sent simultaneously). Because dir listing is cached, the "stat worker" parallelization should probably be controlled separately from http parallelization.

The number of simultaneous threads should be configurable, so that the user can specify it for given provider/connection.

**Comment by mtgreenway** [comment]
Are you building cloudfuse with openssl support? Try verifying that that -s is not being set at https://github.com/LabAdvComp/cloudfuse/blob/master/cloudfuse.c#L665.

There is a good chance that operations are still blocking on something else but it is worth checking that first.

**Comment by Thinkscape** [comment]
I'm using https://github.com/TurboGit/hubicfuse fork. I'm recompiling now and investigating ...

**Comment by Thinkscape** [comment]
Ok, so now I've recompiled it neatly ...
````
$ ./configure
...
checking openssl/crypto.h usability... yes
checking openssl/crypto.h presence... yes
checking for openssl/crypto.h... yes
...
checking for XML... yes
checking for CURL... yes
checking for FUSE... yes
checking for JSON... yes
checking for OPENSSL... yes
````


And run a debug session with:
> hubicfuse /hubic -o -d -f -o auto_unmount -o entry_timeout=120 -o attr_timeout=120 -o ac_attr_timeout=120 -o max_background=4 -o no_remote_lock

Purrs like a kitten! :+1: 

Awesome job and sorry for the noise (also thx @TurboGit for the hubic fork)
